// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Viem from "../bindings/Viem.res.mjs";
import * as QueryHelpers from "./QueryHelpers.res.mjs";
import * as BigIntHelpers from "../bindings/BigIntHelpers.res.mjs";
import * as S$RescriptSchema from "rescript-schema/src/S.res.mjs";

var blockFieldOptionsSchema = S$RescriptSchema.union([
      S$RescriptSchema.literal("number"),
      S$RescriptSchema.literal("hash"),
      S$RescriptSchema.literal("parent_hash"),
      S$RescriptSchema.literal("nonce"),
      S$RescriptSchema.literal("sha3_uncles"),
      S$RescriptSchema.literal("logs_bloom"),
      S$RescriptSchema.literal("transactions_root"),
      S$RescriptSchema.literal("state_root"),
      S$RescriptSchema.literal("receipts_root"),
      S$RescriptSchema.literal("miner"),
      S$RescriptSchema.literal("difficulty"),
      S$RescriptSchema.literal("total_difficulty"),
      S$RescriptSchema.literal("extra_data"),
      S$RescriptSchema.literal("size"),
      S$RescriptSchema.literal("gas_limit"),
      S$RescriptSchema.literal("gas_used"),
      S$RescriptSchema.literal("timestamp"),
      S$RescriptSchema.literal("uncles"),
      S$RescriptSchema.literal("base_fee_per_gas")
    ]);

var blockFieldSelectionSchema = S$RescriptSchema.array(blockFieldOptionsSchema);

var transactionFieldOptionsSchema = S$RescriptSchema.union([
      S$RescriptSchema.literal("block_hash"),
      S$RescriptSchema.literal("block_number"),
      S$RescriptSchema.literal("from"),
      S$RescriptSchema.literal("gas"),
      S$RescriptSchema.literal("gas_price"),
      S$RescriptSchema.literal("hash"),
      S$RescriptSchema.literal("input"),
      S$RescriptSchema.literal("nonce"),
      S$RescriptSchema.literal("to"),
      S$RescriptSchema.literal("transaction_index"),
      S$RescriptSchema.literal("value"),
      S$RescriptSchema.literal("v"),
      S$RescriptSchema.literal("r"),
      S$RescriptSchema.literal("s"),
      S$RescriptSchema.literal("max_priority_fee_per_gas"),
      S$RescriptSchema.literal("max_fee_per_gas"),
      S$RescriptSchema.literal("chain_id"),
      S$RescriptSchema.literal("cumulative_gas_used"),
      S$RescriptSchema.literal("effective_gas_price"),
      S$RescriptSchema.literal("gas_used"),
      S$RescriptSchema.literal("contract_address"),
      S$RescriptSchema.literal("logs_bloom"),
      S$RescriptSchema.literal("type"),
      S$RescriptSchema.literal("root"),
      S$RescriptSchema.literal("status"),
      S$RescriptSchema.literal("sighash")
    ]);

var transactionFieldSelectionSchema = S$RescriptSchema.array(transactionFieldOptionsSchema);

var logFieldOptionsSchema = S$RescriptSchema.union([
      S$RescriptSchema.literal("removed"),
      S$RescriptSchema.literal("log_index"),
      S$RescriptSchema.literal("transaction_index"),
      S$RescriptSchema.literal("transaction_hash"),
      S$RescriptSchema.literal("block_hash"),
      S$RescriptSchema.literal("block_number"),
      S$RescriptSchema.literal("address"),
      S$RescriptSchema.literal("data"),
      S$RescriptSchema.literal("topic0"),
      S$RescriptSchema.literal("topic1"),
      S$RescriptSchema.literal("topic2"),
      S$RescriptSchema.literal("topic3")
    ]);

var logFieldSelectionSchema = S$RescriptSchema.array(logFieldOptionsSchema);

var fieldSelectionSchema = S$RescriptSchema.object(function (s) {
      return {
              block: s.f("block", S$RescriptSchema.option(blockFieldSelectionSchema)),
              transaction: s.f("transaction", S$RescriptSchema.option(transactionFieldSelectionSchema)),
              log: s.f("log", S$RescriptSchema.option(logFieldSelectionSchema))
            };
    });

var logParamsSchema = S$RescriptSchema.object(function (s) {
      return {
              address: s.f("address", S$RescriptSchema.option(S$RescriptSchema.array(Viem.Address.schema))),
              topics: s.f("topics", S$RescriptSchema.array(S$RescriptSchema.array(Viem.Topic.schema)))
            };
    });

var transactionParamsSchema = S$RescriptSchema.object(function (s) {
      return {
              from: s.f("from", S$RescriptSchema.option(S$RescriptSchema.array(Viem.Address.schema))),
              to: s.f("to", S$RescriptSchema.option(S$RescriptSchema.array(Viem.Address.schema))),
              sighash: s.f("sighash", S$RescriptSchema.option(S$RescriptSchema.array(S$RescriptSchema.string)))
            };
    });

var postQueryBodySchema = S$RescriptSchema.object(function (s) {
      return {
              fromBlock: s.f("from_block", S$RescriptSchema.$$int),
              toBlockExclusive: s.f("to_block", S$RescriptSchema.option(S$RescriptSchema.$$int)),
              logs: s.f("logs", S$RescriptSchema.option(S$RescriptSchema.array(logParamsSchema))),
              transactions: s.f("transactions", S$RescriptSchema.option(S$RescriptSchema.array(transactionParamsSchema))),
              fieldSelection: s.f("field_selection", fieldSelectionSchema),
              maxNumLogs: s.f("max_num_logs", S$RescriptSchema.option(S$RescriptSchema.$$int)),
              includeAllBlocks: s.f("include_all_blocks", S$RescriptSchema.option(S$RescriptSchema.bool))
            };
    });

var QueryTypes = {
  blockFieldOptionsSchema: blockFieldOptionsSchema,
  blockFieldSelectionSchema: blockFieldSelectionSchema,
  transactionFieldOptionsSchema: transactionFieldOptionsSchema,
  transactionFieldSelectionSchema: transactionFieldSelectionSchema,
  logFieldOptionsSchema: logFieldOptionsSchema,
  logFieldSelectionSchema: logFieldSelectionSchema,
  fieldSelectionSchema: fieldSelectionSchema,
  logParamsSchema: logParamsSchema,
  transactionParamsSchema: transactionParamsSchema,
  postQueryBodySchema: postQueryBodySchema
};

var blockDataSchema = S$RescriptSchema.object(function (s) {
      return {
              number: s.f("number", S$RescriptSchema.option(S$RescriptSchema.$$int)),
              hash: s.f("hash", S$RescriptSchema.option(S$RescriptSchema.string)),
              parentHash: s.f("parent_hash", S$RescriptSchema.option(S$RescriptSchema.string)),
              nonce: s.f("nonce", S$RescriptSchema.option(S$RescriptSchema.$$null(S$RescriptSchema.$$int))),
              sha3Uncles: s.f("sha3_uncles", S$RescriptSchema.option(S$RescriptSchema.string)),
              logsBloom: s.f("logs_bloom", S$RescriptSchema.option(S$RescriptSchema.string)),
              transactionsRoot: s.f("transactions_root", S$RescriptSchema.option(S$RescriptSchema.string)),
              stateRoot: s.f("state_root", S$RescriptSchema.option(S$RescriptSchema.string)),
              receiptsRoot: s.f("receipts_root", S$RescriptSchema.option(S$RescriptSchema.string)),
              miner: s.f("miner", S$RescriptSchema.option(S$RescriptSchema.string)),
              difficulty: s.f("difficulty", S$RescriptSchema.option(S$RescriptSchema.$$null(BigIntHelpers.schema))),
              totalDifficulty: s.f("total_difficulty", S$RescriptSchema.option(S$RescriptSchema.$$null(BigIntHelpers.schema))),
              extraData: s.f("extra_data", S$RescriptSchema.option(S$RescriptSchema.string)),
              size: s.f("size", S$RescriptSchema.option(BigIntHelpers.schema)),
              gasLimit: s.f("gas_limit", S$RescriptSchema.option(BigIntHelpers.schema)),
              gasUsed: s.f("gas_used", S$RescriptSchema.option(BigIntHelpers.schema)),
              timestamp: s.f("timestamp", S$RescriptSchema.option(BigIntHelpers.schema)),
              uncles: s.f("unclus", S$RescriptSchema.option(S$RescriptSchema.$$null(S$RescriptSchema.string))),
              baseFeePerGas: s.f("base_fee_per_gas", S$RescriptSchema.option(S$RescriptSchema.$$null(BigIntHelpers.schema)))
            };
    });

var transactionDataSchema = S$RescriptSchema.object(function (s) {
      return {
              blockHash: s.f("block_hash", S$RescriptSchema.option(S$RescriptSchema.string)),
              blockNumber: s.f("block_number", S$RescriptSchema.option(S$RescriptSchema.$$int)),
              from: s.f("from", S$RescriptSchema.option(S$RescriptSchema.$$null(S$RescriptSchema.string))),
              gas: s.f("gas", S$RescriptSchema.option(BigIntHelpers.schema)),
              gasPrice: s.f("gas_price", S$RescriptSchema.option(S$RescriptSchema.$$null(BigIntHelpers.schema))),
              hash: s.f("hash", S$RescriptSchema.option(S$RescriptSchema.string)),
              input: s.f("input", S$RescriptSchema.option(S$RescriptSchema.string)),
              nonce: s.f("nonce", S$RescriptSchema.option(S$RescriptSchema.$$int)),
              to: s.f("to", S$RescriptSchema.option(S$RescriptSchema.$$null(S$RescriptSchema.string))),
              transactionIndex: s.f("transaction_index", S$RescriptSchema.option(S$RescriptSchema.$$int)),
              value: s.f("value", S$RescriptSchema.option(BigIntHelpers.schema)),
              v: s.f("v", S$RescriptSchema.option(S$RescriptSchema.$$null(S$RescriptSchema.string))),
              r: s.f("r", S$RescriptSchema.option(S$RescriptSchema.$$null(S$RescriptSchema.string))),
              s: s.f("s", S$RescriptSchema.option(S$RescriptSchema.$$null(S$RescriptSchema.string))),
              maxPriorityFeePerGas: s.f("max_priority_fee_per_gas", S$RescriptSchema.option(S$RescriptSchema.$$null(BigIntHelpers.schema))),
              maxFeePerGas: s.f("max_fee_per_gas", S$RescriptSchema.option(S$RescriptSchema.$$null(BigIntHelpers.schema))),
              chainId: s.f("chain_id", S$RescriptSchema.option(S$RescriptSchema.$$null(S$RescriptSchema.$$int))),
              cumulativeGasUsed: s.f("cumulative_gas_used", S$RescriptSchema.option(BigIntHelpers.schema)),
              effectiveGasPrice: s.f("effective_gas_price", S$RescriptSchema.option(BigIntHelpers.schema)),
              gasUsed: s.f("gas_used", S$RescriptSchema.option(BigIntHelpers.schema)),
              contractAddress: s.f("contract_address", S$RescriptSchema.option(S$RescriptSchema.$$null(S$RescriptSchema.string))),
              logsBoom: s.f("logs_bloom", S$RescriptSchema.option(S$RescriptSchema.string)),
              type_: s.f("type", S$RescriptSchema.option(S$RescriptSchema.$$null(S$RescriptSchema.$$int))),
              root: s.f("root", S$RescriptSchema.option(S$RescriptSchema.$$null(S$RescriptSchema.string))),
              status: s.f("status", S$RescriptSchema.option(S$RescriptSchema.$$null(S$RescriptSchema.$$int))),
              sighash: s.f("sighash", S$RescriptSchema.option(S$RescriptSchema.$$null(S$RescriptSchema.string)))
            };
    });

var logDataSchema = S$RescriptSchema.object(function (s) {
      return {
              removed: s.f("removed", S$RescriptSchema.option(S$RescriptSchema.$$null(S$RescriptSchema.bool))),
              index: s.f("log_index", S$RescriptSchema.option(S$RescriptSchema.$$int)),
              transactionIndex: s.f("transaction_index", S$RescriptSchema.option(S$RescriptSchema.$$int)),
              transactionHash: s.f("transaction_hash", S$RescriptSchema.option(S$RescriptSchema.string)),
              blockHash: s.f("block_hash", S$RescriptSchema.option(S$RescriptSchema.string)),
              blockNumber: s.f("block_number", S$RescriptSchema.option(S$RescriptSchema.$$int)),
              address: s.f("address", S$RescriptSchema.option(S$RescriptSchema.string)),
              data: s.f("data", S$RescriptSchema.option(S$RescriptSchema.string)),
              topic0: s.f("topic0", S$RescriptSchema.option(S$RescriptSchema.$$null(Viem.Topic.schema))),
              topic1: s.f("topic1", S$RescriptSchema.option(S$RescriptSchema.$$null(Viem.Topic.schema))),
              topic2: s.f("topic2", S$RescriptSchema.option(S$RescriptSchema.$$null(Viem.Topic.schema))),
              topic3: s.f("topic3", S$RescriptSchema.option(S$RescriptSchema.$$null(Viem.Topic.schema)))
            };
    });

var dataSchema = S$RescriptSchema.object(function (s) {
      return {
              blocks: s.f("blocks", S$RescriptSchema.option(S$RescriptSchema.array(blockDataSchema))),
              transactions: s.f("transactions", S$RescriptSchema.option(S$RescriptSchema.array(transactionDataSchema))),
              logs: s.f("logs", S$RescriptSchema.option(S$RescriptSchema.array(logDataSchema)))
            };
    });

var queryResponseSchema = S$RescriptSchema.object(function (s) {
      return {
              data: s.f("data", S$RescriptSchema.array(dataSchema)),
              archiveHeight: s.f("archive_height", S$RescriptSchema.$$int),
              nextBlock: s.f("next_block", S$RescriptSchema.$$int),
              totalTime: s.f("total_execution_time", S$RescriptSchema.$$int)
            };
    });

var ResponseTypes = {
  blockDataSchema: blockDataSchema,
  transactionDataSchema: transactionDataSchema,
  logDataSchema: logDataSchema,
  dataSchema: dataSchema,
  queryResponseSchema: queryResponseSchema
};

function executeHyperSyncQuery(serverUrl, postQueryBody) {
  return QueryHelpers.executeFetchRequest(serverUrl + "/query", "POST", [
              postQueryBody,
              postQueryBodySchema
            ], queryResponseSchema, undefined);
}

var responseSchema = S$RescriptSchema.object(function (s) {
      return s.f("height", S$RescriptSchema.$$int);
    });

async function getArchiveHeight(serverUrl) {
  return await QueryHelpers.executeFetchRequest(serverUrl + "/height", "GET", undefined, responseSchema, undefined);
}

export {
  QueryTypes ,
  ResponseTypes ,
  executeHyperSyncQuery ,
  getArchiveHeight ,
}
/* blockFieldOptionsSchema Not a pure module */
