// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S$RescriptSchema from "rescript-schema/src/S.res.mjs";

var schema = S$RescriptSchema.transform(S$RescriptSchema.setName(S$RescriptSchema.string, "BigInt"), (function (s) {
        return {
                p: (function (str) {
                    try {
                      return BigInt(str);
                    }
                    catch (_exn){
                      return s.fail("The string is not valid bigint", undefined);
                    }
                  }),
                s: (function (v) {
                    return v.toString();
                  })
              };
      }));

export {
  schema ,
}
/* schema Not a pure module */
