// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

var rootDomain = "https://sourcify.dev/server";

var endpoint = rootDomain + "/verify/etherscan";

async function verify(data) {
  var response = await fetch(endpoint, {
        method: "POST",
        body: Caml_option.some(Belt_Option.getExn(JSON.stringify(data))),
        headers: Caml_option.some(new Headers({
                  "Content-type": "application/json"
                }))
      });
  return await response.json();
}

var VerifyEtherscan = {
  endpoint: endpoint,
  verify: verify
};

var endpoint$1 = rootDomain + "/check-all-by-addresses";

async function check(addresses, chainIds) {
  var queryParams = "?addresses=" + addresses + "&chainIds=" + chainIds;
  var responseRaw = await fetch(endpoint$1 + queryParams);
  return await responseRaw.json();
}

var CheckByAddresses = {
  endpoint: endpoint$1,
  check: check
};

var endpoint$2 = rootDomain + "/files/any";

async function getFiles(chain, address) {
  var url = endpoint$2 + ("/" + chain + "/" + address);
  var response = await fetch(url);
  return await response.json();
}

var FilesByAddress = {
  endpoint: endpoint$2,
  getFiles: getFiles
};

async function testVerifyEtherscan() {
  var response = await verify({
        address: "0x67c349467D639A9e0822c079Aee8DF9964308BC9",
        chainId: "137"
      });
  console.log(response);
}

async function testCheckByAddresses() {
  var response = await check("0x67c349467D639A9e0822c079Aee8DF9964308BC9", "137");
  console.log(response);
}

async function testFilesByAddress() {
  var response = await getFiles("137", "0x67c349467D639A9e0822c079Aee8DF9964308BC9");
  console.log("files by address", response);
}

var Examples = {
  testVerifyEtherscan: testVerifyEtherscan,
  testCheckByAddresses: testCheckByAddresses,
  testFilesByAddress: testFilesByAddress
};

export {
  rootDomain ,
  VerifyEtherscan ,
  CheckByAddresses ,
  FilesByAddress ,
  Examples ,
}
/* No side effect */
