// Generated by ReScript, PLEASE EDIT WITH CARE

import * as HyperLink from "../components/HyperLink.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function BlockPage$Block(props) {
  var blockData = props.blockData;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx(HyperLink.make, {
                              children: blockData.blockNumber,
                              href: "#"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("span", {
                                      children: "timestamp: "
                                    }),
                                blockData.blockTimestamp
                              ]
                            })
                      ],
                      className: "flex flex-col"
                    }),
                JsxRuntime.jsx("div", {
                      children: blockData.txCount
                    })
              ],
              className: "flex"
            });
}

var Block = {
  make: BlockPage$Block
};

function BlockPage(props) {
  var blocks = [{
      blockNumber: 1,
      blockTimestamp: 2,
      txCount: 3
    }];
  return JsxRuntime.jsxs("div", {
              children: [
                "Blocks",
                JsxRuntime.jsx("div", {
                      children: blocks.map(function (blockData) {
                            return JsxRuntime.jsx(BlockPage$Block, {
                                        blockData: blockData
                                      });
                          })
                    })
              ]
            });
}

var make = BlockPage;

export {
  Block ,
  make ,
}
/* HyperLink Not a pure module */
