// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function ChainSelect(props) {
  Curry._1({
        Amoy: 80002,
        Arbitrum: 42161,
        "Arbitrum Nova": 42170,
        "Arbitrum Sepolia": 421614,
        Aurora: 1313161554,
        Avalanche: 43114,
        Base: 8453,
        "Base Sepolia": 84532,
        "Berachain Artio": 80085,
        Blast: 81457,
        "Blast Sepolia": 168587773,
        Boba: 288,
        BSC: 56,
        "C1 Milkomeda": 2001,
        Canto: 25,
        Celo: 42220,
        Crab: 44,
        Cronos: 25,
        Cyber: 7560,
        Darwinia: 46,
        Degen: 666666666,
        ETH: 1,
        Fantom: 250,
        "Fhenix Testnet": 42069,
        Flare: 14,
        Gnosis: 100,
        "Gnosis Chiado": 10200,
        Goerli: 5,
        "Harmony Shard 0": 1666600000,
        "Harmony Shard 1": 1666600001,
        Hedera: 295,
        Holesky: 17000,
        "Immutable zkEVM": 13371,
        "Inco Testnet": 9090,
        Kava: 2222,
        Klaytn: 8217,
        Kroma: 255,
        Linea: 59144,
        Lukso: 42,
        Manta: 169,
        Mantle: 5000,
        Metis: 1088,
        Moonbeam: 1284,
        Mumbai: 80001,
        "Neon EVM": 245022934,
        "OKBC Testnet": 195,
        OpBNB: 204,
        Optimism: 10,
        "Optimism Sepolia": 11155420,
        Polygon: 137,
        "Polygon zkEVM": 1101,
        Publicgoods: 424,
        RSK: 30,
        Scroll: 534352,
        Sepolia: 11155111,
        "Shimmer EVM": 148,
        "Taiko Jolnr": 1088,
        "X Layer": 196,
        Zeta: 7000,
        "Zircuit Testnet": 48899,
        zkSync: 324,
        Zora: 7777777
      }, undefined);
  var match = React.useState(function () {
        return "";
      });
  var selectedChain = match[0];
  var match$1 = React.useState(function () {
        return "";
      });
  var setRpcUrl = match$1[1];
  var rpcUrl = match$1[0];
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Select a Blockchain and connection method",
                      className: "text-2xl font-bold mb-4"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("label", {
                              children: "Enter RPC URL",
                              className: "block text-sm font-medium text-gray-700"
                            }),
                        JsxRuntime.jsx("input", {
                              className: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm",
                              placeholder: "Enter custom RPC URL",
                              type: "text",
                              value: rpcUrl,
                              onChange: (function (e) {
                                  setRpcUrl(e.target.value);
                                })
                            })
                      ],
                      className: "mb-4 w-full max-w-md"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("button", {
                              children: "Use RPC URL",
                              className: "flex-1 px-4 py-2 mb-2 sm:mb-0 bg-blue-500 text-white font-medium rounded-md shadow-sm hover:bg-blue-600 focus:outline-none",
                              onClick: (function (param) {
                                  console.log("Selected RPC URL: " + rpcUrl);
                                })
                            }),
                        JsxRuntime.jsx("button", {
                              children: "Use HyperSync",
                              className: "flex-1 px-4 py-2 mb-2 sm:mb-0 bg-blue-500 text-white font-medium rounded-md shadow-sm hover:bg-blue-600 focus:outline-none",
                              onClick: (function (param) {
                                  console.log("Selected HyperSync Chain: " + selectedChain);
                                })
                            }),
                        JsxRuntime.jsx("button", {
                              children: "Use Firehose",
                              className: "flex-1 px-4 py-2 mb-2 sm:mb-0 bg-green-500 text-white font-medium rounded-md shadow-sm hover:bg-green-600 focus:outline-none",
                              onClick: (function (param) {
                                  console.log("Unimplemented: Firehose");
                                })
                            }),
                        JsxRuntime.jsx("button", {
                              children: "Use Subquid",
                              className: "flex-1 px-4 py-2 bg-purple-500 text-white font-medium rounded-md shadow-sm hover:bg-purple-600 focus:outline-none",
                              onClick: (function (param) {
                                  console.log("Unimplemented: Subquid");
                                })
                            })
                      ],
                      className: "flex flex-col sm:flex-row sm:space-x-4 w-full max-w-md"
                    })
              ],
              className: "flex flex-col items-center justify-center min-h-screen bg-gray-100 p-4"
            });
}

var make = ChainSelect;

export {
  make ,
}
/* react Not a pure module */
