// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Buttons(props) {
  var onClick = props.onClick;
  return JsxRuntime.jsx("button", {
              children: props.text,
              className: "bg-black px-4 py-1 m-2 text-primary border-primary border w-40 hover:bg-primary hover:text-black hover:border-2",
              onClick: (function (param) {
                  onClick();
                })
            });
}

var make = Buttons;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
