// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function CopyButton(props) {
  var __className = props.className;
  var textToCopy = props.textToCopy;
  var className = __className !== undefined ? __className : "";
  return JsxRuntime.jsx("button", {
              children: "📋",
              className: "px-[5px] py-[4px] mx-[5px] hover:bg-white active:bg-black " + className,
              onClick: (function (param) {
                  navigator.clipboard.writeText(textToCopy);
                })
            });
}

var make = CopyButton;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
