// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Donate(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("a", {
                    children: "💜 donate to eth berlin - dezent.eth",
                    className: "text-primary text-xxs",
                    href: "https://etherscan.io/address/0x59cc3Fc56B8B2988F259EC1E6f3446907130f728",
                    rel: "no-opener no-referrer",
                    target: "_"
                  }),
              className: "absolute bottom right-0 p-2 "
            });
}

var make = Donate;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
