// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

async function tryResolveEnsHandle(address) {
  try {
    var resp = await fetch("https://ensdata.net/" + address, {
          method: "GET",
          headers: Caml_option.some(new Headers({
                    "Content-type": "application/json"
                  }))
        });
    if (resp.ok) {
      return (await resp.json()).address;
    } else {
      return address;
    }
  }
  catch (exn){
    return address;
  }
}

function ENSData(props) {
  var address = props.address;
  var match = React.useState(function () {
        return address;
      });
  var setDisplayAddress = match[1];
  var displayAddress = match[0];
  React.useEffect((function () {
          tryResolveEnsHandle(displayAddress).then(function (ensData) {
                setDisplayAddress(function (param) {
                      return ensData;
                    });
                return Promise.resolve(undefined);
              });
        }), [address]);
  return displayAddress;
}

var make = ENSData;

export {
  tryResolveEnsHandle ,
  make ,
}
/* react Not a pure module */
