// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function HyperLink(props) {
  return JsxRuntime.jsx("a", {
              children: props.children,
              className: "font-medium text-blue-600 dark:text-blue-500 hover:underline",
              href: props.href
            });
}

var make = HyperLink;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
