// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Time from "./Time.res.mjs";
import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function PrettyDisplay$TextUserInput(props) {
  var userInput = props.userInput;
  var typedInput = Time.useTypedCharactersString(100, userInput);
  var totalTime = Math.imul(100, userInput.length) + 200 | 0;
  var match = React.useState(function () {
        return false;
      });
  Time.useDelayedState(totalTime, match[1], true);
  return JsxRuntime.jsxs("span", {
              children: [
                typedInput,
                match[0] ? null : JsxRuntime.jsx("span", {
                        children: "_",
                        className: "ml-1 w-1 h-full bg-white opacity-30"
                      })
              ]
            });
}

var TextUserInput = {
  make: PrettyDisplay$TextUserInput
};

function PrettyDisplay$QuestionTyped(props) {
  var __timeTillAnswered = props.timeTillAnswered;
  var timeTillAnswered = __timeTillAnswered !== undefined ? __timeTillAnswered : 1000;
  var match = React.useState(function () {
        return false;
      });
  var answered = match[0];
  Time.useDelayedState(timeTillAnswered, match[1], true);
  return JsxRuntime.jsxs("p", {
              children: [
                JsxRuntime.jsx("span", {
                      children: answered ? ">" : "?",
                      className: "text-green-500"
                    }),
                " " + props.prompt + ": ",
                JsxRuntime.jsx(Time.DelayedDisplay.make, {
                      delay: 500,
                      children: JsxRuntime.jsx("span", {
                            children: JsxRuntime.jsx(PrettyDisplay$TextUserInput, {
                                  userInput: props.answer
                                }),
                            className: answered ? "text-blue-500" : ""
                          })
                    })
              ]
            });
}

var QuestionTyped = {
  make: PrettyDisplay$QuestionTyped
};

export {
  TextUserInput ,
  QuestionTyped ,
}
/* Time Not a pure module */
