// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Button from "./Button.res.mjs";
import * as BlockPage from "./pages/BlockPage.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  var page = Routes.usePage();
  if (typeof page !== "object") {
    if (page === "ChainSelect") {
      return JsxRuntime.jsxs(JsxRuntime.Fragment, {
                  children: [
                    JsxRuntime.jsx("p", {
                          children: "select"
                        }),
                    JsxRuntime.jsx(ChainSelect.make, {})
                  ]
                });
    } else {
      return JsxRuntime.jsx("p", {
                  children: "unknown"
                });
    }
  }
  switch (page.TAG) {
    case "Search" :
        return JsxRuntime.jsx("p", {
                    children: "search"
                  });
    case "Block" :
        return JsxRuntime.jsx("p", {
                    children: "block"
                  });
    case "Address" :
        return JsxRuntime.jsx("p", {
                    children: "address - " + page._1 + " on chain: " + page._0.toString()
                  });
    case "Transaction" :
        return JsxRuntime.jsx("p", {
                    children: "tx"
                  });
    case "Error" :
        return JsxRuntime.jsx("p", {
                    children: page._0
                  });
    
  }
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "What is this about?",
                      className: "text-3xl font-semibold"
                    }),
                JsxRuntime.jsx("p", {
                      children: "This is a simple template for a Vite project using ReScript & Tailwind CSS."
                    }),
                JsxRuntime.jsx("h2", {
                      children: "Fast Refresh Test",
                      className: "text-2xl font-semibold mt-5"
                    }),
                JsxRuntime.jsx(Button.make, {
                      children: Caml_option.some("count is " + match[0].toString()),
                      onClick: (function (param) {
                          setCount(function (count) {
                                return count + 1 | 0;
                              });
                        })
                    }),
                JsxRuntime.jsxs("p", {
                      children: [
                        "Edit ",
                        JsxRuntime.jsx("code", {
                              children: "src/App.res"
                            }),
                        " and save to test Fast Refresh."
                      ]
                    }),
                JsxRuntime.jsx(BlockPage.make, {})
              ],
              className: "p-6"
            });
}

var make = App;

export {
  make ,
}
/* Routes Not a pure module */
