// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Routes from "./router/Routes.res.mjs";
import * as ChainSelect from "./pages/ChainSelect.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.res.mjs";

function App(props) {
  React.useState(function () {
        return 0;
      });
  RescriptReactRouter.useUrl(undefined, undefined);
  var page = Routes.usePage();
  if (typeof page !== "object") {
    if (page === "ChainSelect") {
      return JsxRuntime.jsxs(JsxRuntime.Fragment, {
                  children: [
                    JsxRuntime.jsx("p", {
                          children: "select"
                        }),
                    JsxRuntime.jsx(ChainSelect.make, {})
                  ]
                });
    } else {
      return JsxRuntime.jsx("p", {
                  children: "unknown"
                });
    }
  }
  switch (page.TAG) {
    case "Search" :
        return JsxRuntime.jsx("p", {
                    children: "search"
                  });
    case "Block" :
        return JsxRuntime.jsx("p", {
                    children: "block"
                  });
    case "Address" :
        return JsxRuntime.jsx("p", {
                    children: "address - " + page._1 + " on chain: " + page._0.toString()
                  });
    case "Transaction" :
        return JsxRuntime.jsx("p", {
                    children: "tx"
                  });
    case "Error" :
        return JsxRuntime.jsx("p", {
                    children: page._0
                  });
    
  }
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
