// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.res.mjs";
import * as React from "react";
import * as Donate from "./components/Donate.res.mjs";
import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";

import './styles/index.css'
;

import './styles/remove-default.css'
;

var domElement = document.querySelector("#root");

if (!(domElement == null)) {
  Client.createRoot(domElement).render(JsxRuntime.jsxs(React.StrictMode, {
            children: [
              JsxRuntime.jsx(App.make, {}),
              JsxRuntime.jsx(Donate.make, {})
            ]
          }));
}

export {
  
}
/*  Not a pure module */
